### ISSUE TITLE
Custom Epic Games Install Folder not working

### ISSUE THREAD

**Issue by Colossalcow91** [jaydenmilne/steamsync#11]
Hi! I'm trying to use the steamsync exe, with custom install folders for Steam and Epic Games. When I run it, I get the error "the path 'D;/Games/Epic Games/Data/Manifests' does not exist, is that an actual epic games store install directory?" Any advice? That is my actual Epic Games install directory.

**Comment by jaydenmilne** [comment]
Not sure if you just fat fingered writing it up, but the path should be ‘D:/Games’…

Is that your issue?

**Comment by jaydenmilne** [comment]
Going to close as "can't reproduce"

**Comment by jkingsbury1000** [comment]
Hi, I'm having this issue as well. My Epic Games install is on D: but I'm also getting the message "the path 'D;/Games/Epic Games/Data/Manifests' does not exist, is that an actual epic games store install directory?"

**Comment by jaydenmilne** [comment]
Yours also has a semicolon, it should be a colon ‘:’. Is that the issue?
