### ISSUE TITLE
GTAV doesn't launch

### ISSUE THREAD

**Issue by jaydenmilne** [jaydenmilne/steamsync#2]
GTAV doesn't launch because apparently some authentication needs to happen through the EGL before it will work, verified by looking at the command line arguments that invoke `PlayGTAV.exe`, there are some tokens passed in from the EGL.

It seems that we can work around this by using the URI format that the Epic Games Launcher uses when you make a shortcut (Library -> 3 dot menu -> create shortcut)

Instead of the target being

`D:\Epic Games\GTAV\PlayGTAV.exe` 

it should be

`com.epicgames.launcher://apps/9d2d0eb64d5c44529cece33fe2a46482?action=launch&silent=true`

Where `9d2d0....` is the `AppName` field of the `.item` file (see https://jayd.ml/games/2020/05/16/epic-games-store-steam-libraries.html)

We're already collecting the `AppName` (I figured it would be useful) so we should change the link format we inject into `shortcuts.vdf`. That will break the picture previews in steam coming from the `.exe` though, which would be sad.

**Comment by jaydenmilne** [comment]
See https://jayd.ml/games/2020/05/19/epicgamesstore-uri.html

**Comment by jaydenmilne** [comment]
Good news: If we give Steam the path to the executable as the icon path, it will load them from the `.exe`! 🎉🎉🎉

**Comment by jaydenmilne** [comment]
Fixed in `0.2.0`

**Comment by pythoninthegrass** [comment]
Nice work!
