### ISSUE TITLE
Optional Arugments for Itch.io (and other platforms) integrations are inactive.

### ISSUE THREAD

**Issue by apurplecaboose** [jaydenmilne/steamsync#28]
When trying to use the CIL to add itch.io games into the steam library the optional arguments are not recognized. Only Epic Games Store integration is currently working.

**Comment by jaydenmilne** [comment]
Did you install it from pip? The pip version is out of date

**Comment by apurplecaboose** [comment]
I did install via pip according to the documentation. How would you recommend me install it then?

**Comment by Orangestar12** [comment]
Is there a reason why the pip module hasn't been maintained despite being recommended in the documentation?

**Comment by jaydenmilne** [comment]
I couldn’t figure out python packaging and rage quit. I’ve actually been working on this and am very close to having an updateOn Feb 26, 2023, at 02:44, Orangestar12 ***@***.***> wrote:﻿
Is there a reason why the pip module hasn't been maintained despite being recommended in the documentation?

**Comment by jaydenmilne** [comment]
Just released 0.4.1 which is up-to-date.
