### ISSUE TITLE
Icons in Big Picture

### ISSUE THREAD

**Issue by kosuke26** [jaydenmilne/steamsync#29]
Is it able to set game’s icon in Big Picture instead of a default icon?
![FE2F096C-36D6-4A3F-A9D3-4559212B2BCE](https://user-images.githubusercontent.com/15405556/176817482-4cd3cccf-f02a-4148-b385-c85077e5ea5b.jpeg)

**Comment by jaydenmilne** [comment]
If you are using the cli and the `--download-art` option, it should
