### ISSUE TITLE
Forgive me my ineptitude

### ISSUE THREAD

**Issue by Xenogor** [jaydenmilne/steamsync#30]
Please help. I'm trying to figure all this out, but (despite pushing 30) I'm kinda very new at this. Trying to learn, know a little java and a little HTML, but more than a bit rusty on both of those. Want to learn as much as I can through modding, not sure what language I'm working with or how to dig into all of it proper to fix whatever this issue is. At a precursory glance, I don't notice anything amiss. Here's what I'm looking at.

Immediate edit: I placed shortcuts.vdf in the indicated folder earlier and got this, it was originally a much larger block before I gleaned that bit of information. I'm sure I'm just overlooking something and need a pair of trained eyes to find it for me.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

steamsync v0.3.0 -  Encountered An Error. Please submit a bug report at https://github.com/jaydenmilne/steamsync/issues with this log!
Traceback (most recent call last):

  File "main.py", line 150, in add_shortcuts

  File "steamsync.py", line 367, in add_games_to_shortcut_file

KeyError: 'shortcuts'


Log:

steampath C:\Program Files (x86)\Steam
manifestPath C:\ProgramData\Epic\EpicGamesLauncher\Data\Manifests
Scanning EGS manifest store (C:\ProgramData\Epic\EpicGamesLauncher\Data\Manifests)...
Collected 3 games from the EGS manifest store

⚠ ⚠ NOTICE: ⚠ ⚠
Using the path to the executable instead of the Epic Games Launcher URI
You may experience issues with online games (eg GTAV!)

Exception!!!

**Comment by jaydenmilne** [comment]
This can happen if there isn’t already some shortcuts in the UI. Try manually making one (press the + button at the bottom of the library screen).

**Comment by Xenogor** [comment]
Sick. Got it working. Thanks, man!

**Comment by jaydenmilne** [comment]
Cool
