### ISSUE TITLE
max() arg is an empty sequence exception failure

### ISSUE THREAD

**Issue by SecondReality** [jaydenmilne/steamsync#4]
It does not work, seemingly due to an exception.

Command used: `steamsync.py --all`

9 games were found.

`Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\Scripts\steamsync.py", line 437, in <module>
    add_games_to_shortcut_file(
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\Scripts\steamsync.py", line 358, in add_games_to_shortcut_file
    last_index = int(max(shortcuts["shortcuts"].keys()))
ValueError: max() arg is an empty sequence`

OS: Windows 10
My steam/epic installations are at their default folder paths.

**Comment by jaydenmilne** [comment]
I'm going to hazard a guess that this is because you have no shortcuts in Steam alread

**Comment by jaydenmilne** [comment]
I pushed a change in steamsync 0.2.4, please try upgrading it and let me know if it resolves your issue (`python -m pip install --upgrae steamsync`

**Comment by SecondReality** [comment]
> I pushed a change in steamsync 0.2.4, please try upgrading it and let me know if it resolves your issue (`python -m pip install --upgrae steamsync`

That did work, thank you @jaydenmilne
